# Generated by Django 5.2.6 on 2025-09-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='publicado_em',
            new_name='publicado',
        ),
    ]
