# Generated by Django 5.2.6 on 2025-09-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_publicado_em_livro_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
