# Generated by Django 5.2.6 on 2025-09-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome',
            new_name='titulo',
        ),
    ]
