# Generated by Django 5.2.6 on 2025-09-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_nome_livro_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='nome_autor',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_usuario',
        ),
    ]
